# Generated by Django 5.0.3 on 2024-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_file_deleted_alter_folder_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cost',
            field=models.BigIntegerField(),
        ),
    ]
